### ISSUE TITLE
sleighzy.zookeeper return AnsibleUndefinedVariable

### ISSUE THREAD

**Issue by Raawaan** [sleighzy/ansible-zookeeper#25]
i'm trying to install and run zookeeper using this ansile galaxy, it returns 
`fatal:FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ groups['zookeeper-nodes'] }}: 'dict object' has no attribute 'zookeeper-nodes'"}
`

**Comment by sleighzy** [comment]
Hi @Raawaan , thanks for raising an issue. Let me know what the resolution was in the end if you like, or if just a docs problem that could have been a bit clearer. Thanks.

**Comment by Raawaan** [comment]
i added "zookeeper-nodes" to my hosts file as mentioned, sorry for interruption.
thanks!
