### ISSUE TITLE
Support zookeeper > 3.4.14

### ISSUE THREAD

**Issue by diogopms** [sleighzy/ansible-zookeeper#3]
I'm trying to install zookeeper 3.5.5 but the download mirror is not working.

**Details:**

[Code](https://github.com/sleighzy/ansible-zookeeper/blob/f157afb246e8a6f0c1d10695989b8ab08b987cd2/tasks/main.yaml#L25
)

http://apache.mirror.anlx.net/zookeeper/zookeeper-3.5.5/
Name: apache-zookeeper-3.5.5.tar.gz  

VS

http://apache.mirror.anlx.net/zookeeper/zookeeper-3.4.14/
Name: zookeeper-3.4.14.tar.gz

Maybe one possible solution is passing the filename as a custom variable

What do you think?

**Comment by sleighzy** [comment]
Alternatively could bump version to 3.5.5 (probably need to do anyway to stay up-to-date) and update the filename at the same time given they've changed this.

**Comment by diogopms** [comment]
I can open a PR with this fix.
Is that ok for you?

**Comment by sleighzy** [comment]
Yes please, would be much appreciated.

**Comment by sleighzy** [comment]
Ansible role is now upgraded to ZooKeeper 3.5.6 and the file locations and name updated to reflect the ZooKeeper downloads. Have added Molecule testing framework to this as well to assist in catching these going forwards.
