### ISSUE TITLE
'ansible.vars.hostvars.HostVarsVars object' has no attribute 'zookeeper_id'"}

### ISSUE THREAD

**Issue by arkachat** [sleighzy/ansible-zookeeper#5]
TASK [ansible-zookeeper : Template configuration file to zoo.cfg] ***********************************************************************************************
fatal: [35.192.83.190]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'zookeeper_id'"}

**Comment by sleighzy** [comment]
Thanks for the raising issue, I’ll attempt to replicate on my end. Can you please provide further info on the playbook, inventory, and any group vars or host vars files you may be using when running this role.

**Comment by arkachat** [comment]
Sure.

**Comment by arkachat** [comment]
Defaults:

---
zookeeper_mirror: https://www-eu.apache.org/dist/zookeeper
zookeeper_version: 3.5.6
zookeeper_package: apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz

zookeeper_group: zookeeper
zookeeper_user: zookeeper

zookeeper_root_dir: /usr/share
zookeeper_install_dir: '{{ zookeeper_root_dir }}/apache-zookeeper-{{ zookeeper_version }}'
# The zookeeper_dir is created as a symlik to the actual installation directory.
# All other configuration and variables use the symlinked directory.
zookeeper_dir: '{{ zookeeper_root_dir }}/zookeeper'
zookeeper_log_dir: /var/log/zookeeper

# Variables for templating zookeeper.conf.j2
zookeeper_data_dir: /var/lib/zookeeper
zookeeper_data_log_dir: /var/lib/zookeeper
zookeeper_client_port: 2181

# Uniquely identifies the ZooKeeper instance when clustering ZooKeeper nodes.
# This value is placed in the /var/lib/zookeeper/myid file.
zookeeper_id: 1

zookeeper_leader_port: 2888
zookeeper_election_port: 3888

zookeeper_servers: "{{groups['zookeeper-nodes']}}"
zookeeper_environment: {}


Hosts:
[zookeeper-nodes]
35.192.83.190

**Comment by sleighzy** [comment]
Thanks for that. Sincere apologies for the delay, I have been able to replicate and am working on a fix.

I will be pushing out an updated role to use ZooKeeper 3.6 first as the current default version is no longer available as a download from their releases page.

**Comment by sleighzy** [comment]
@arkachat , should be resolved in master now.

**Comment by sleighzy** [comment]
Note that master will now have version 3.6.0 of ZooKeeper as I have upgraded this in a recent PR.

**Comment by arkachat** [comment]
Thanks a lot Simon.
