### ISSUE TITLE
Can't install role with custom name

### ISSUE THREAD

**Issue by edgarasg** [sleighzy/ansible-zookeeper#51]
```
Starting galaxy role install process
- extracting community.zookeeper to ...
[WARNING]: - community.zookeeper was NOT installed successfully: Invalid linkname for tarfile member: path ...ansible-zookeeper is not a subpath of the role ...community.zookeeper
```

Seems related to https://github.com/sleighzy/ansible-zookeeper/blob/master/tests/roles/ansible-zookeeper being a symlink, can this be fixed?

**Comment by sleighzy** [comment]
Thanks for the report @edgarasg   I’ve merged in that PR and re-published to Ansible Galaxy now. Could you please retry and let me know how you get on.

**Comment by edgarasg** [comment]
Yes, installation completes successfully now, thanks.
